# Generated by Django 6.0.2 on 2026-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='target_role',
        ),
        migrations.AddField(
            model_name='notice',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('student', 'Students'), ('faculty', 'Faculty')], default='all', max_length=20),
        ),
    ]
