# Generated by Django 6.0.2 on 2026-03-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_options_rename_content_notice_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('student', 'Students'), ('faculty', 'Faculty'), ('admin', 'Admins')], default='all', max_length=20),
        ),
    ]
